-- ============================================
-- MIGRATION: Add Barter Requests & Ratings
-- Run this in Supabase SQL Editor on your
-- existing database (no reset needed)
-- ============================================

-- 1. Barter Requests Table
CREATE TABLE IF NOT EXISTS public.barter_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    to_user_id    BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    barter_id     BIGINT REFERENCES public.barter(id) ON DELETE SET NULL,
    message       TEXT DEFAULT '',
    status        TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Ratings Table
CREATE TABLE IF NOT EXISTS public.ratings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    to_user_id    BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    rating        INTEGER CHECK (rating >= 1 AND rating <= 5),
    review        TEXT DEFAULT '',
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(from_user_id, to_user_id)
);

-- 3. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_barter_requests_to ON public.barter_requests(to_user_id);
CREATE INDEX IF NOT EXISTS idx_barter_requests_from ON public.barter_requests(from_user_id);
CREATE INDEX IF NOT EXISTS idx_ratings_to ON public.ratings(to_user_id);

-- 4. Enable RLS (Row Level Security) - optional but recommended
-- ALTER TABLE public.barter_requests ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;

-- Done! Your database now supports barter requests and ratings.

-- 5. Random Seed Ratings (for demonstration)
INSERT INTO public.ratings (from_user_id, to_user_id, rating, review) VALUES
(2, 1, 5, 'Rani is an excellent teacher! Her tailoring skills are top-notch.'),
(3, 1, 4, 'Great exchange! Learned some very practical tailoring tips.'),
(4, 2, 5, 'Alice explains embroidery so simply. Highly recommended!'),
(5, 2, 4, 'Very patient and helpful teacher.'),
(1, 3, 5, 'Bob knows everything about organic farming. So much to learn.'),
(2, 3, 5, 'Amazing yoga sessions, feeling much more flexible.'),
(5, 4, 4, 'Charlie is great with computer basics. Very helpful for beginners.'),
(1, 5, 5, 'Diana is a true artist. Her dance sessions are inspiring!');
