-- Database Reset and Seed Script
-- Consolidates all tables and initial data into a single file

-- 1. DROP EXISTING TABLES
DROP TABLE IF EXISTS public.roadmap CASCADE;
DROP TABLE IF EXISTS public.barter CASCADE;
DROP TABLE IF EXISTS public.interview_results CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;

-- 2. CREATE USERS TABLE
CREATE TABLE public.users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    email        TEXT UNIQUE NOT NULL,
    password     TEXT NOT NULL,
    skills       TEXT[] DEFAULT '{}',
    location     TEXT DEFAULT '',
    bio          TEXT DEFAULT '',
    career_goal  TEXT DEFAULT '',
    profile_img  TEXT DEFAULT '',
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CREATE JOBS TABLE
CREATE TABLE public.jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           TEXT NOT NULL,
    icon            TEXT DEFAULT 'heart',
    required_skills JSONB DEFAULT '[]'::jsonb,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. CREATE COURSES TABLE
CREATE TABLE public.courses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    provider   TEXT NOT NULL,
    duration   TEXT NOT NULL,
    link       TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. CREATE BARTER TABLE
CREATE TABLE public.barter (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer         TEXT NOT NULL,
    want          TEXT NOT NULL,
    location      TEXT NOT NULL,
    teaching_mode TEXT DEFAULT 'In-Person',
    user_id       BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. CREATE ROADMAP TABLE
CREATE TABLE public.roadmap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    skill_name      TEXT NOT NULL,
    status          TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed')),
    course_name     TEXT DEFAULT '',
    course_provider TEXT DEFAULT '',
    course_link     TEXT DEFAULT '',
    target_date     DATE,
    notes           TEXT DEFAULT '',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. CREATE INTERVIEW RESULTS TABLE
CREATE TABLE public.interview_results (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    career_intent   TEXT,
    session_data    JSONB NOT NULL,
    total_score     INTEGER,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. CREATE BARTER REQUESTS TABLE
DROP TABLE IF EXISTS public.barter_requests CASCADE;
CREATE TABLE public.barter_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    to_user_id    BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    barter_id     BIGINT REFERENCES public.barter(id) ON DELETE SET NULL,
    message       TEXT DEFAULT '',
    status        TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. CREATE RATINGS TABLE
DROP TABLE IF EXISTS public.ratings CASCADE;
CREATE TABLE public.ratings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    to_user_id    BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    rating        INTEGER CHECK (rating >= 1 AND rating <= 5),
    review        TEXT DEFAULT '',
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(from_user_id, to_user_id)
);

-- 10. INDEXES
CREATE INDEX idx_interview_results_user ON public.interview_results(user_id);
CREATE INDEX idx_roadmap_user ON public.roadmap(user_id);
CREATE INDEX idx_barter_requests_to ON public.barter_requests(to_user_id);
CREATE INDEX idx_barter_requests_from ON public.barter_requests(from_user_id);
CREATE INDEX idx_ratings_to ON public.ratings(to_user_id);

-- 9. SEED DATA

-- Users
INSERT INTO public.users (name, email, password, skills, location, bio, career_goal) VALUES
('Rani Priya',    'john@example.com',    '1234567890', '{"Tailoring", "Cooking"}',        'Bangalore', 'Mother of 2, loves helping people', 'Tailoring Specialist'),
('Alice Kumar',   'alice@example.com',   '1234567890', '{"Embroidery", "Teaching"}',       'Chennai',   'School teacher passionate about crafts', 'Digital Trainer'),
('Bob Sharma',    'bob@example.com',     '1234567890', '{"Organic Farming", "Yoga"}',      'Pune',      'Farmer with 10 years experience', 'Organic Farmer'),
('Charlie Nair',  'charlie@example.com', '1234567890', '{"Computer Basics", "Math"}',      'Hyderabad', 'Digital literacy advocate', 'Data Entry Specialist'),
('Diana Pillai',  'diana@example.com',   '1234567890', '{"Classical Dance", "Art"}',       'Kerala',    'Performer and art teacher', 'Handicraft Artisan');

-- Jobs
INSERT INTO public.jobs (title, icon, required_skills) VALUES
('Community Health Worker',  'heart',    '["caring", "communication", "patience", "basic health", "local language"]'::jsonb),
('Solar Technician',         'sun',      '["technical", "electrical", "problem solving", "physical fitness", "safety awareness"]'::jsonb),
('Digital Trainer',          'computer', '["teaching", "computer basics", "internet", "patience", "communication"]'::jsonb),
('Organic Farmer',           'leaf',     '["farming", "patience", "nature", "hard work", "planning"]'::jsonb),
('Handicraft Artisan',       'heart',    '["creativity", "sewing", "embroidery", "painting", "patience"]'::jsonb),
('Early Childhood Educator', 'heart',    '["teaching", "caring", "storytelling", "patience", "creativity"]'::jsonb),
('Data Entry Specialist',    'computer', '["typing", "attention to detail", "computer basics", "english"]'::jsonb),
('Cloud Kitchen Chef',       'heart',    '["cooking", "hygiene", "planning", "time management", "quality control"]'::jsonb),
('Event Planner',            'clock',    '["organization", "communication", "networking", "budgeting", "creativity"]'::jsonb);

-- Courses
INSERT INTO public.courses (name, provider, duration, link) VALUES
('Basic Healthcare Training',  'Red Cross',            '3 Months', 'https://example.com/health'),
('Solar Panel Installation',   'Skill India',          '6 Weeks',  'https://example.com/solar'),
('Computer Literacy 101',      'Google Digital Garage','4 Weeks',  'https://example.com/digital'),
('Organic Farming Basics',     'Agri University',      '2 Months', 'https://example.com/farming'),
('Advanced Embroidery',        'Local Artisan Guild',  '1 Month',  'https://example.com/art'),
('Child Development',          'IGNOU',                '6 Months', 'https://example.com/child'),
('Typing Masterclass',         'Udemy',                '2 Weeks',  'https://example.com/typing');

-- Barter Listings
INSERT INTO public.barter (offer, want, location, teaching_mode, user_id) VALUES
('Tailoring',             'Computer Basics',       'Bangalore', 'In-Person', 1),
('Cooking South Indian',  'English Speaking',      'Mysore',    'In-Person', 1),
('Embroidery',            'Web Design Help',       'Chennai',   'Online',    2),
('Teaching Math',         'Sewing',                'Chennai',   'Both',      2),
('Organic Farming Tips',  'Digital Marketing',     'Pune',      'In-Person', 3),
('Yoga Classes',          'Accounting Help',       'Pune',      'Both',      3),
('Computer Basics',       'Guitar Lessons',        'Hyderabad', 'Online',    4),
('Math Tutoring',         'Driving Lessons',       'Hyderabad', 'In-Person', 4),
('Classical Dance',       'Photography',           'Kerala',    'In-Person', 5),
('Fabric Painting',       'Content Writing',       'Kerala',    'Online',    5),
('Pickle Making',         'Online Selling',        'Mumbai',    'In-Person', 1),
('Home Gardening',        'Video Editing',         'Delhi',     'Online',    3),
('Knitting',              'Graphic Design',        'Kolkata',   'Both',      2),
('Pottery',               'Social Media Marketing','Jaipur',    'In-Person', 5),
('Saree Draping',         'Financial Planning',    'Hyderabad', 'Both',      1),
('Vegetable Carving',     'MS Office',             'Goa',       'Online',    4),
('Soap Making',           'E-commerce Setup',      'Pune',      'Both',      3),
('Candle Making',         'Business Strategy',     'Delhi',     'Online',    2),
('Jewelry Making',        'Resume Writing',        'Mumbai',    'In-Person', 5),
('Baking Cakes',          'App Development Guide', 'Bangalore', 'Both',      4);

-- Roadmap
INSERT INTO public.roadmap (user_id, skill_name, status, course_name, course_provider, course_link, notes) VALUES
(1, 'Computer Basics',    'in_progress', 'Computer Literacy 101',     'Google Digital Garage', 'https://example.com/digital', 'Learning to use email and internet'),
(1, 'English Speaking',   'planned',     '',                           '',                      '',                            'Want to communicate with city clients'),
(2, 'Web Design',         'planned',     '',                           '',                      '',                            'For online business'),
(3, 'Digital Marketing',  'in_progress', '',                           '',                      '',                            'Growing farm business online'),
(4, 'Guitar',             'planned',     '',                           '',                      '',                            'Hobby goal'),
(5, 'Photography',        'in_progress', '',                           '',                      '',                            'For dance recital promotions'),
(5, 'Content Writing',    'planned',     '',                           '',                      '',                            'To write about classical arts');